
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tracker.Data
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_eventlineup
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_eventlineup()
    {

        this.tbl_artisthistory = new HashSet<tbl_artisthistory>();

    }


    public int Lineup_ID { get; set; }

    public int Event_ID { get; set; }

    public int Artist_ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_artisthistory> tbl_artisthistory { get; set; }

    public virtual tbl_artists tbl_artists { get; set; }

    public virtual tbl_events tbl_events { get; set; }

}

}
