
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tracker.Data
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_artisthistory
{
        [Key]
    public int ArtistHistory_ID { get; set; }

    public string User_ID { get; set; }

    public int Event_ID { get; set; }

    public int EventLineup_ID { get; set; }

    public int Artist_ID { get; set; }



    public virtual tbl_artists tbl_artists { get; set; }

    public virtual tbl_events tbl_events { get; set; }

    public virtual tbl_eventlineup tbl_eventlineup { get; set; }

}

}
